apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.openshift }}
    app.openshift.io/vcs-uri: "https://github.com/0xERR0R/blocky.git"
    app.openshift.io/vcs-ref: "{{ .Values.image.tag | default .Chart.AppVersion }}"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "blocky.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "blocky.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "blocky.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-udp
              containerPort: {{ .Values.service.dnsPort }}
              protocol: UDP
            - name: dns-tcp
              containerPort: {{ .Values.service.dnsPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP

          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
              {{- toYaml . | nindent 12 }}
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
              readOnly: true
            - name: cache
              mountPath: /app/cache
            - name: logs
              mountPath: /logs
      volumes:
        - name: config
          configMap:
            name: {{ include "blocky.fullname" . }}
        - name: cache
          {{- if .Values.persistence.cache.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.cache.existingClaim | default (printf "%s-cache" (include "blocky.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.logs.existingClaim | default (printf "%s-logs" (include "blocky.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
