{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "blocky.fullname" . }}
    weight: 100
{{- end }}
