{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "blocky.fullname" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "blocky.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.config.prometheus.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
